/ (Root)
├── bin/ (Essential user binaries)
├── boot/ (Boot loader files)
├── dev/ (Device files)
├── etc/ (Configuration files)
├── home/ (User home directories)
├── lib/ (Essential shared libraries)
├── media/ (Mount point for removable media)
├── mnt/ (Temporary mount point)
├── opt/ (Optional application packages)
├── root/ (Root user's home directory)
├── sbin/ (System administration binaries)
├── srv/ (Service-specific data)
├── tmp/ (Temporary files)
├── usr/ (User utilities and applications)
│   ├── bin/ (User binaries)
│   ├── include/ (Header files for C/C++)
│   ├── lib/ (User shared libraries)
│   └── sbin/ (Non-essential system admin binaries)
└── var/ (Variable data)
    ├── cache/ (Cached data)
    ├── log/ (Log files)
    ├── spool/ (Spooling data, e.g., print queues)
    └── tmp/ (Temporary files (often persistent across reboots))
